language: node_js
node_js:
- 'node'
- '7'
cache:
  directories:
  - node_modules
# deploy:
#   provider: heroku
#   api_key: "from terminal run 'travis encrypt $(heroku api_key) --add deploy.api_key'
#   on: dist
#   app: my-app-123
#   run: npm run build
before_install:
- npm i -g npm@6.2.0
install:
- npm install
script:
- npm test